#!/bin/bash -x
TS=$(date +"%Y%m%d%H%M%S")
cd bulk
mkdir "../remote/data$TS"
appcfg.py download_data \
	--url=http://ferdinandmotel.appspot.com/_ah/remote_api \
	--oauth2 \
	--filename="data$TS" \
	--result_db_filename="../remote/data$TS/datastore.db"
mv bulkloader* ./trash/

